spring.application.name=Marker-system

# H2 baza yolu Render-d?ki daimi disk? (persistent disk) yön?ldilir:
spring.datasource.url=jdbc:h2:file:/var/data/markerdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.main.allow-bean-definition-overriding=true

# Port t?nziml?m?sini d? ?lav? etm?yi unutmay?n:
server.port=${PORT:8080}

#gemini.api.keys=
#gemini.model=gemini-3.6-flash